using UnityEngine;
using System;


[Serializable]
public class EnemyType
{
    [SerializeField]
    private GameObject _enemy;
    [SerializeField]
    private int _count;

    private Opponent _opponent;

    public int GetEnemyToughness()
    {
        if (_opponent == null)
        {
            _opponent = _enemy.GetComponent<Opponent>();
        }

        float toughness = Mathf.Round((_opponent.Hp / 10) / 2);
        return (int)toughness;
    }

    public GameObject GetEnemyObject()
    {
        return _enemy;
    }
    public int Count
    {
        get { return _count; }
    }

}
